### ISSUE TITLE
Luxor can't render some unicode characters

### ISSUE THREAD

**Issue by schneiderfelipe** [JuliaGraphics/Luxor.jl#125]
Hi,

I couldn't make Luxor (v2.6.0) properly render `C₁`. Instead of the subscript, a white rectangle is shown. This happens to PNG, SVG, and PDF outputs:

```julia
using Luxor

@svg begin
	label("C1", :N, Point(0, 0))
	label("C₁", :S, Point(0, 0))
end 100 100

@png begin
	label("C1", :N, Point(0, 0))
	label("C₁", :S, Point(0, 0))
end 100 100

@pdf begin
	label("C1", :N, Point(0, 0))
	label("C₁", :S, Point(0, 0))
end 100 100
```

The PNG output (the other two are similar):
![C1](https://user-images.githubusercontent.com/37125/103043832-15814300-455d-11eb-8d63-2b334388a5da.png)

**Comment by cormullion** [comment]
I can't reproduce this on my Mac:

<img width="173" alt="Screenshot 2020-12-23 at 23 49 49" src="https://user-images.githubusercontent.com/52289/103044736-91898400-4579-11eb-955f-fade8ee3d6a2.png">

so I'm guessing you're using a different OS and, because you haven't specified a font, the default font is used which doesn't have that character. Perhaps:

```
@svg begin
	fontface("JuliaMono")
	label("C1", :N, Point(0, 0))
	label("C₁", :S, Point(0, 0))
end 100 100
``` 

will solve it... :)

**Comment by schneiderfelipe** [comment]
I'm on Ubuntu 20.04.1 LTS. `fontface("JuliaMono")` has no effect for me (I'm pretty sure I don't have this font), but `fontface("Dejavu Sans")` works, thanks!

![C1](https://user-images.githubusercontent.com/37125/103045418-2cc32f00-4563-11eb-893e-8643c2233131.png)

I thought that Dejavu would be [the default font](http://juliagraphics.github.io/Luxor.jl/stable/text/#The-Toy-API) on Ubuntu. How do I check which is the currently selected font?

**Comment by cormullion** [comment]
There isn’t as far as I’m aware a function in Cairo.jl that can return the current font, so Luxor can’t help here. I think `fontconfig` will be involved somewhere (on Linux), but the whole business of trying to reliably specify fonts on all three platforms is a frustrating business with few good solutions. I think you’ll have to manually manage font selections and always remember to set a font at the start of a drawing. I usually do that anyway because I don’t want Helvetica...  😅

**Comment by schneiderfelipe** [comment]
> There isn’t as far as I’m aware a function in Cairo.jl that can return the current font, so Luxor can’t help here. I think `fontconfig` will be involved somewhere (on Linux), but the whole business of trying to reliably specify fonts on all three platforms is a frustrating business with few good solutions. I think you’ll have to manually manage font selections and always remember to set a font at the start of a drawing. I usually do that anyway because I don’t want Helvetica... sweat_smile

Interesting! I'll always set my font from the beginning from now on. Thanks!
