### ISSUE TITLE
@draw rejects width and height as variables

### ISSUE THREAD

**Issue by schneiderfelipe** [JuliaGraphics/Luxor.jl#127]
The following example throws an error:

```julia
width, height = 250, 250
@draw begin
	for i in 1:10
		randomhue()
		radius = 50
		center = Point(rand(-250:250), rand(-250:250))
		star(center, radius, 5, 0.5, 0, :fill)
	end
# end 250 250
end width height
```

```
MethodError: no method matching CairoARGBSurface(::typeof(Graphics.width), ::typeof(Graphics.height))

Closest candidates are:

CairoARGBSurface(::Any) at /home/schneider/.julia/packages/Cairo/smWIA/src/Cairo.jl:275

    Luxor.Drawing(::Function, ::Function, ::Symbol, ::String)@drawings.jl:22
    Luxor.Drawing(::Function, ::Function, ::Symbol)@drawings.jl:16
    macro expansion@drawings.jl:595[inlined]
    top-level scope@Local: 3[inlined]
    top-level scope@WorkspaceManager.jl:0
```

Swapping the last two lines (uncommenting `# end 250 250`) gives the expected result:

![stars](https://user-images.githubusercontent.com/37125/103768496-5c614500-5001-11eb-9c0f-0055237b164e.png)

**Comment by cormullion** [comment]
Yes, this is because `@draw` is a convenient short-cut macro, and doesn't expand variables. For all drawings where you want to parameterize dimensions, batch-process filenames, specify transparent backgrounds, etc., you have to use the `Drawing().... finish()` form. I don't think I can easily improve the error messages here...

**Comment by schneiderfelipe** [comment]
Oh, I see. I didn't know that it doesn't expand variables. Is that a Julia thing? By the way, maybe that information could go to the [`@draw` docstring](https://juliagraphics.github.io/Luxor.jl/latest/basics/#Luxor.@draw)?

**Comment by cormullion** [comment]
Macros are cool, but here they're used more for the beginner with some easy syntax (so that a single macro call can do some set up and tidy up tasks), but as soon as you want to get into passing/expanding variables through them it can get tricky. It might be possible of course, I'm no expert. :) 

I could add something to the docstrings...
