### ISSUE TITLE
`preview()` .svg files on jupyter notebook

### ISSUE THREAD

**Issue by sclereid** [JuliaGraphics/Luxor.jl#15]
Previewing a svg file on IJulia results in opening the file by default program on my platform. 
I read that:
```julia
"""
    preview()

If working in Jupyter (IJUlia), display a PNG file in the notebook.
On macOS, open the file, which probably uses the default, Preview.app.
On Unix, open the file with `xdg-open`.
On Windows, pass the filename to `explorer`.
"""
function preview()
    if isdefined(Main, :IJulia) && Main.IJulia.inited && currentdrawing.surfacetype == "png"
        display(load(currentdrawing.filename))
 ...
```
*But why shouldn't it pass the file to jupyter*? For me, ``open luxor-drawing.svg`` will open it with an outdated Adobe Illustrator, which is contrary to my expectations. Opening in on a web browser should even create a better experience.

**Comment by cormullion** [comment]
Yes this area is interesting, and difficult, because of the OS. On my Mac, SVGs always open in a web browser. I don't really know why. I know I can tell my Mac to open certain files in certain apps, (using Finder/GetInfo) but I don't know how much a Julia program can do to override this process.

**Comment by sclereid** [comment]
Actually, I would prefer to store the output image inside the notebook. Is this also difficult?

**Comment by cormullion** [comment]
I'll look into it.

**Comment by cormullion** [comment]
SVGs are mostly loading in the notebook now:

![screen shot 2017-05-02 at 19 01 43](https://cloud.githubusercontent.com/assets/52289/25631928/dbc38086-2f69-11e7-98d8-2715a4d66568.png)

There's a slight problem in Jupyter if you send too much data all at once - I suppose SVGs by their nature can be very bulky, compared with PNGs. That issue is at https://github.com/JuliaLang/IJulia.jl/issues/534...

I'll test and upload this later today.

**Comment by cormullion** [comment]
Looks like the speed limit problem in IJulia has been fixed in master, which will get into a release before long.
