### ISSUE TITLE
Colored edges on black text

### ISSUE THREAD

**Issue by FeldrinH** [JuliaGraphics/Luxor.jl#153]
Testing this example given in the docs:
```julia
@png begin
     fontsize(50)
     circle(Point(0, 0), 150, :stroke)
     text("hello world", halign=:center, valign=:middle)
end
```
I noticed that the rendered text has slight red and blue edges instead of being completely black as I would have expected.

Image as rendered on my system:
![image](https://user-images.githubusercontent.com/5256211/115627908-6edd6100-a308-11eb-9fae-e58138212485.png)

Zoomed-in screenshot of text:
![image](https://user-images.githubusercontent.com/5256211/115627834-58cfa080-a308-11eb-91aa-de5e92f302a3.png)

Looking at the example image shown in the docs, the text there appears to be completely black.

I suspect this is something related to my setup, maybe something with Windows ClearType. (I am running julia 1.6.0 with latest Luxor.jl on Windows 10)

Is there some configuration to disable this or can this be fixed somehow? This seems like an unintended thing and at least for my use is problematic.

**Comment by cormullion** [comment]
On MacOS it looks like this:

<img width="1430" alt="Screenshot 2021-04-22 at 07 38 04" src="https://user-images.githubusercontent.com/52289/115668072-8c2d2200-a33e-11eb-8635-88a8d0c7e650.png">

so I think you're right to suggest that it's something to do with Windows ClearType. (As you probably know, ClearType uses subpixel rendering, switching the individual red, green, and blue subpixels on and off to draw the edges of font outlines with a little more accuracy.)

Of the various output formats supported by Luxor, PNG is the only one where text is rasterized. The SVG format converts text to graphic paths, and the PDF/EPS formats delay or postpone the rasterization until the document is actually viewed.

You could experiment with using functions like `textoutlines()`, which converts the text to graphic paths (and presumably avoids the rasterization process).

```
 textoutlines("hello world", O, halign=:center, valign=:middle, :fill)
```

There's a `setantialias()` function which allows you to control the antialiasing of graphics (not text), and this will use the grey-scale antialiasing, not the fancy colour techniques of ClearType.

I think there _may_ be options in the underlying Cairo library to control some aspects of the font rasterization process; if these are also implemented in Cairo.jl you'll be able to call them from Julia - otherwise you should open an issue at https://github.com/JuliaGraphics/Cairo.jl/issues . (However, I think it's fair to say that Cairo.jl's font handling is fairly basic, so you might have to add a fair amount of code.)

**Comment by FeldrinH** [comment]
Yes, using textoutlines does resolve the problem very nicely.

However, it is a little scary to know that the default font rendering is affected by system font rendering settings. I would have expected text rendering on a graphics library to be deterministic and independent of the system configuration.

I'm gonna take a look at the underlying Cairo options if I have some time.

In the meantime, a small remark in the docs about the fact that the `text()` function is affected by ClearType and possibly other system font rendering settings seems like a good idea.
