### ISSUE TITLE
placeimage() doesn't work as expected

### ISSUE THREAD

**Issue by Sov-trotter** [JuliaGraphics/Luxor.jl#155]
Hey all! I am trying to use the `placeimage()` function to place an image matrix over a drawing.
But I think the current approach here https://github.com/JuliaGraphics/Luxor.jl/blob/3d6b98348a1b7ba852c801d6ef205773fb6e454c/src/images.jl#L194 might be a little buggy? 

The image placement is good as long as it has square dimensions(the image to be placed)
eg: `placeimage(img, centered=true, Point(0,0))`
In the following image the matrix with the black background has dimensions 250*250 
![placeimage_centered](https://user-images.githubusercontent.com/43717431/121308956-41339200-c91f-11eb-97cb-8fd40532411b.png)

However for a matrix with dimensions 350*250, the image center is skewed.

![placeimage_centered_350*250](https://user-images.githubusercontent.com/43717431/121309306-a7b8b000-c91f-11eb-9b37-65a057a38ed3.png)

**Comment by cormullion** [comment]
Indeed, it might be a little buggy.

**Comment by cormullion** [comment]
```
using Luxor

img = @imagematrix begin
    background("red")
end 400 150

@draw begin
     h, w = size(img)
     pt = Point(O.x - (w/2), O.y - (h/2))
     placeimage(img, pt)
end
```

<img width="234" alt="Screenshot 2021-06-09 at 10 24 22" src="https://user-images.githubusercontent.com/52289/121329175-e09b5980-c90c-11eb-8c4d-d71c158ba93a.png">

I think the problem here is the usual width/height|row/column shenanigans that's been confusing everyone since forever 😃. `img` here is a wide image that will report its dimensions as `size(img) = (150, 400)` (150 rows × 400 columns), and these will be interpreted as `w = 150` and `h=400` by `placeimage()`. 

So I suppose a simple fix would be to swap them round, with the risk that everyone else's images will be flipped. Or you could use `placeimage(img'...)` to flip the matrix first...

**Comment by Sov-trotter** [comment]
Yeah. This tends to be quite confusing. 

I was able to fix it at my end though though a simple workaround.
Since I already have the width and height of the image matrix, I don't need to use the `size` function. 
Borrowing the `centered=true` approach
`placeimage(img, Point(pos.x -  width/2, pos.y -  height/2), centered = false)` works
So basically we pass the already centered points to the `placeimage` function
