### ISSUE TITLE
Darkened edges on color shape

### ISSUE THREAD

**Issue by guo-yong-zhi** [JuliaGraphics/Luxor.jl#160]
Looks like a mirror issue of https://github.com/JuliaGraphics/Luxor.jl/issues/153, but may be some differences.
Running the example
```julia
d = Drawing(20, 20, :image)
origin()
background(1,0,0,0)
setcolor(1,0,0,1)
ellipse(Point(0,0), 10, 10, :fill)
mat = image_as_matrix()
finish()
```
I got
![图片](https://user-images.githubusercontent.com/55872791/124535375-94c6cc00-de48-11eb-9c3d-1b34bde1fa41.png)
and
```julia
color.(mat) |> unique
```
![图片](https://user-images.githubusercontent.com/55872791/124535492-c770c480-de48-11eb-8178-e8a082bfd643.png)
Should there be any non red color here? I believe it should be
![图片](https://user-images.githubusercontent.com/55872791/124535704-2c2c1f00-de49-11eb-9aab-29df19fb2fb6.png)

>Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
[ae8d54c2] Luxor v2.12.0

The same problem occurred both on my Windows and Ubuntu.

**Comment by cormullion** [comment]
This isn't really a problem, though, it's more to do with antialiasing. 

|Antialias|Description|PNG|
|:--------|:-----------|:----|
|0|Use the default antialiasing for the subsystem and target device, since 1.0|![antialias-0](https://user-images.githubusercontent.com/52289/124561327-ad79b680-de35-11eb-9fd9-4197427ebc91.png)|
|1|Use a bilevel alpha mask|![antialias-1](https://user-images.githubusercontent.com/52289/124561331-ad79b680-de35-11eb-92fb-86e291a4dd66.png)|
|2|Perform single-color antialiasing|![antialias-2](https://user-images.githubusercontent.com/52289/124561332-ae124d00-de35-11eb-886c-66dbb9a21bca.png)|
|3|Perform antialiasing by taking advantage of the order of subpixel elements|![antialias-3](https://user-images.githubusercontent.com/52289/124561334-ae124d00-de35-11eb-8dce-51a2fa5daf2c.png)|
|4|Hint that the backend should perform some antialiasing but prefer speed over quality|![antialias-4](https://user-images.githubusercontent.com/52289/124561335-ae124d00-de35-11eb-9ef3-3778bd9e4ede.png)|
|5|The backend should balance quality against performance|![antialias-5](https://user-images.githubusercontent.com/52289/124561337-aeaae380-de35-11eb-8526-9eaae7caf2a2.png)|
|6|Hint that the backend should render at the highest quality, sacrificing speed if necessary|![antialias-6](https://user-images.githubusercontent.com/52289/124561339-aeaae380-de35-11eb-9923-1fb0ea7fd82f.png)|

For this particular example, there are three different results: values of 0, 2, 3, 5, 6 use 17 colours, value 1 ("bilevel") used 2 colours, and value 4 ("speed over quality") used 13.

By the way, the Cairo docs say:

> Set the antialiasing mode of the rasterizer used for drawing shapes. This value is a hint, and a particular backend may or may not support a particular value. At the current time, no backend supports CAIRO_ANTIALIAS_SUBPIXEL when drawing shapes.

so I don't think it's totally predictable in any case.

**Comment by guo-yong-zhi** [comment]
None of the list match my "believing style" above... Either my intuition is wrong, or the world is wrong. My intuition comes from that if we further place it to a pure red background image, it should be completely invisible. So, it should not contain colors other than red.
Anyway, that seems to be a convincing conclusion. Thank you very much.
