### ISSUE TITLE
Luxor.Sequence() is not defined

### ISSUE THREAD

**Issue by lcookiel** [JuliaGraphics/Luxor.jl#179]
Using [Sequence()](https://github.com/JuliaGraphics/Luxor.jl/blob/43997ffeb7cadd23b60c38b91dd5077d5d94d54a/src/animate.jl#L1-L12) function gives an error:

```
using Luxor

demo = Sequence(400, 400, "test")
```

```
UndefVarError: Sequence not defined

Stacktrace:
 [1] top-level scope
   @ In[8]:1
 [2] eval
   @ ./boot.jl:360 [inlined]
 [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1116
```

**Comment by cormullion** [comment]
What versions are you using?

**Comment by lcookiel** [comment]
Oh, I see now, I was looking at documentation for version 0.7. Thanks a lot for drawing my attention.
Probably would be better to add some warning signs at previous versions' documentations that the method is deprecated, and that in later versions Movie() should be used.

**Comment by cormullion** [comment]
Yes, that could be a nice addition to Documenter.jl. (The Julia manual does something similar (but opposite) for forthcoming versions.)

In theory (because Julia is aiming for reproducible computing environments for science) there's nothing to stop you using Julia 0.4 and Luxor 0.8, referring to the appropriate documents, but in practice that's not ideal - the latest is _usually_ the least worst. 😂
