### ISSUE TITLE
Shifting existing drawing to center

### ISSUE THREAD

**Issue by kilacoda** [JuliaGraphics/Luxor.jl#227]
Hi,

I have a figure like this, which is created by simply using `poly` in a loop:
![1](https://user-images.githubusercontent.com/14952412/175360738-3ef91e47-120f-4f40-a669-263d4211cb36.svg)

I'd like to center the image produced at some coordinate of the polygons in that blob and scale the image a bit larger for more clarity (my ultimate goal is to export this SVG to a PNG and make a GIF out of multiple such images). Is there any way I can do this? I tried `origin(<point>)`  but that seems to set the origin with which all new figures are drawn to be set to (0,0).

**Comment by cormullion** [comment]
Hi. I suppose the way Luxor/Cairo does the drawing can be awkward for some workflows like this  - it's more of a "paint on the canvas and move on" approach, rather than "build objects in memory and then render them" approach. 

I've had some success with stored paths - you build a path on the drawing then store it in a variable. Also, if you have a list of points you can transform them using `polytranslate!`, `polyscale!` et al.  These sometimes can overcome the basic Cairo drawing model.
