### ISSUE TITLE
Incorrect rendering of texts in Pluto markdown cells

### ISSUE THREAD

**Issue by GiggleLiu** [JuliaGraphics/Luxor.jl#228]
The subscripts in the svg plots are not rendered properly in Pluto markdown. 

![image](https://user-images.githubusercontent.com/6257240/177953378-517bffea-607a-4202-8f4b-1e932ee8bf19.png)

The png format looks good, the directly display of svg is also good.

**Comment by cormullion** [comment]
Hi! I have no idea what's going on here. :) 

Without specifying a font for `text()`, I don't see a character, just an empty rectangle.

With a suitable font selected, I see the correct character:

<img width="726" alt="Screenshot 2022-07-08 at 11 02 03" src="https://user-images.githubusercontent.com/52289/177968896-07954825-6acd-44ce-8258-c8c0953ffe98.png">

So what's the default font used by Luxor/Cairo if you don't specify a font before using `text()`? That's a good question, and I don't know the answer. On my MacOS system it appears to use Helvetica (or similar). On Windows perhaps it's Arial. On Unix, might be, well, who knows, perhaps DejaVu. And I don't know which of these fonts include subscript glyphs...

**Comment by GiggleLiu** [comment]
I do not think it is a fontface issue, I tried monospace, JuliaMono-Light, DejaVu et al. None of them works.
I am using Ubuntu 22.04.

**Comment by GiggleLiu** [comment]
![image](https://user-images.githubusercontent.com/6257240/178043596-adfa386f-bcb6-448b-a21a-b46070503a55.png)

I have a better example here.

**Comment by cormullion** [comment]
Ah, have you got more than one SVG image in your notebook?

**Comment by cormullion** [comment]
Might be https://github.com/JuliaPlots/Makie.jl/issues/952 but for Pluto...

**Comment by GiggleLiu** [comment]
> VG image in your notebook?

Yes.

**Comment by GiggleLiu** [comment]
Is it possible to circumvent this issue?

**Comment by cormullion** [comment]
Sorry, I don't know enough about Pluto's Markdown and the use of expressions here.

If you just use simple code cells the SVGs don't look like they interact badly:

<img width="510" alt="Screenshot 2022-07-08 at 21 39 21" src="https://user-images.githubusercontent.com/52289/178067452-086793cd-e752-4c6f-8c63-81be3e6321f2.png">
 
Similarly, if you return a variable holding the drawing, it seems to work OK too:

<img width="411" alt="Screenshot 2022-07-08 at 21 44 36" src="https://user-images.githubusercontent.com/52289/178067776-300192f8-fe04-4b3c-aab9-94193b525d35.png">

Perhaps you could ask the Pluto folks to help? They know more about the interaction between the display system, Markdown, macros, and cells than I will ever do. :)

**Comment by GiggleLiu** [comment]
Hi, @fonsp . We need your help.

**Comment by GiggleLiu** [comment]
Now I am almost sure it is a glyph id problem. This PR is an approach to fix, but it is a kind of dirty fix, which basically replaces the ids using regular expression.

https://github.com/JuliaPlots/CairoMakie.jl/pull/163/files

**Comment by fonsp** [comment]
Hey @GiggleLiu ! Pluto doesn't really have control over how the Markdown stdlib handles interpolation. In this case, the Markdown stdlib runs [this function](https://github.com/JuliaLang/julia/blob/master/stdlib/Markdown/src/render/rich.jl#L17-L19) which writes the SVG contents directly as HTML output. 

You want it to do [this](https://github.com/JuliaLang/julia/blob/cb5f401aaadcd17fbe366a64afdbf7e6fc71ac69/stdlib/Markdown/src/render/rich.jl#L11-L15), replacing `png` with `svg+xml`, which will render the svg in an `<img>` element using a base64-encoded data URI. This is pretty much identical to how Pluto displays the object when it is the result of the cell (i.e. without `md"`).

You could open a PR to julialang/julia to use this method for svg images, or you could add an override into your notebook, or into Luxor.jl. Something like this should work:

```julia
import Markdown
Markdown.tohtml(io::IO, img::Luxor.SVGDrawing) = # replace SVGDrawing with the actual name
    print(io, """<img src="data:image/svg+xml;base64,""")
    print(io, Markdown.stringmime(MIME"image/svg+xml"(), img))
    print(io, "\" />")
end
```

This method overload is not type piracy because it only dispatches on a type from Luxor.jl.
