### ISSUE TITLE
Source code for how to create a graph for inclusion in Luxor Documentation

### ISSUE THREAD

**Issue by StevenSiew** [JuliaGraphics/Luxor.jl#274]
Are you interest in the source code for using Luxor to draw a graph, so that you can include the source code for Luxor Documentation?

Here is what the drawing looks like (see attached file)

![Image027](https://github.com/JuliaGraphics/Luxor.jl/assets/56211719/fcfe0107-9ef6-4ead-8f1d-8f2d932ea710)

**Comment by cormullion** [comment]
Haha, very good! A welcome PR.

I've carefully avoided positioning Luxor as a plotting tool, but ithis is a nice demonstration of graphical possibilities.

A good place to put it would be here: http://juliagraphics.github.io/Luxor.jl/dev/example/moreexamples/ .. 

Personally, I'd adjust the aesthetics a bit - the axes are too heavy, since they're subordinate to the curves. A bit more [Edward Tufte](https://www.edwardtufte.com/tufte/) styling would be welcome!

**Comment by StevenSiew** [comment]
> Personally, I'd adjust the aesthetics a bit - the axes are too heavy,
since they're subordinate to the curves. A bit more Edward Tufte
<https://www.edwardtufte.com/tufte/> styling would be welcome!

You can adjust the thickness yourself. By the way, I do not know who Edward
Tufta is.

The code for the axes window are

    sethue("red")
    setline(4)
    """ Draw the outline of the graph box """
    points = [Point(myplottingarea.xtopleft,myplottingarea.ytopleft),
              Point(myplottingarea.xbotleft,myplottingarea.ybotleft),
              Point(myplottingarea.xbotright,myplottingarea.ybotright)]
    poly(points, :stroke, close=false)
    setline(2)

Anyway let me have some time to put the source code in a textfile so that I
can test it before  sending it to you.

**Comment by StevenSiew** [comment]
Alright, this is my first attempt at sending you the source code.

I will attached a text file to this comment.

My attempt to attached the file "LuxorGraphDemo.jl" has failed

Apparently the comment does not support a file ending with .jl

I will rename LuxorGraphDemo.jl  to  LuxorGraphDemo.txt

Please rename the file back to  LuxorGraphDemo.jl

[LuxorGraphDemo.txt](https://github.com/JuliaGraphics/Luxor.jl/files/12854307/LuxorGraphDemo.txt)

**Comment by cormullion** [comment]
Cool, and thanks. If you want to make further changes, you can now make a Pull Request! - the code is in `data/gallery/` now, and the graphic will be visible in the latest docs build once Github gets round to deploying them (which takes about an hour or more these days). 

I made a few changes, but otherwise it's all your code.

None of the fonts you specified seem to be used in the file I generated - but this is quite usual, they never work properly on someone else's computer.

**Comment by StevenSiew** [comment]
Is there a way for Luxor to read in images directly from the web.
For example:  https://i.imgur.com/xdy68Zg.jpeg

If so can you put the instructions to do so on the Luxor tutorial?

Regards
Steven Siew
