### ISSUE TITLE
Time to release v4?

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Luxor.jl#293]
Now that Julia v1.10 has been released, I think we should have a new release of Luxor - 3.9.0.  This will be the release that no longer runs on any Julia versions **before** 1.9. 

@hyrodium @hustf Do you think this is OK... mentioning you since you guys have contributed to this release!

**Comment by hyrodium** [comment]
I thought the next version would be v4.0, and I couldn't have time to remove operations such as `+(::Point, ::Number)`.
Is it okay to release the next v3.x? (x-ref: https://github.com/JuliaGraphics/Luxor.jl/issues/270#issuecomment-1775355850)

**Comment by cormullion** [comment]
I don’t know … 😂 I think I need someone to decide for me !

**Comment by hustf** [comment]
How characteristically nice of you to ask, cormullion!
 
I have a PR which is in progress. I think my struggles with installation was related to changes in Pkg and my misinformed practice regarding environments. I would prefer to continue work on that PR on Julia 1.9.3+ at some time in the future, because 1.9.4 was when they fixed a related printing issue. From that perspective, Luxor 3.9.0 (or 4.0?) would preferrably skip to requiring >=1.9.4.

I hope Point + Number, BoundaryBox + Float and the like goes away. In the past, I liked to add meters and seconds to points at different scales. Now I think surprising method definitions is not good practice, especially for collections. Some of that previous preference was motivated from immature broadcasting support in paleolithic Julia (and the cool new thing of defining methods willy nilly). If new methods have been defined in Luxor, some of my bad practice of adding units (which are not Real, but Number) to points may be affected in unpredictable ways.

If we are correcting mistakes or ideas implemented earlier that we now don't like anymore, that's not a breaking change, I think. Neither is dropping support of older versions of Julia a breaking change, since users stuck on old Julia will not be affected at all - they will just be left behind.

**Comment by cormullion** [comment]
>How characteristically nice of you to ask, cormullion!

😀❤️ - but I'm also being very indecisive too... :) 

So how about:

- [ ] Add deprecations for things people don't like
- [ ] Make a 3.9 release end of this week
- [ ] Start a 4.0 release with deprecations removed
- [ ] ... that's it
