### ISSUE TITLE
How to split the animation into two animation contexts (two separate canvases in same canvas)?

### ISSUE THREAD

**Issue by mantzaris** [JuliaGraphics/Luxor.jl#31]
I am would like to know if it possible to; have a ball like simulation and a different 'context/pane/section' next to it, which the simulation does not move into, and then in the different area something such as statistics of the balls can then be displayed.

Would that use the 'tiles/partitions'? http://juliagraphics.github.io/Luxor.jl/stable/basics.html#Tiles-and-partitions-1

The partitions and tiles seem to provide the position context but does the algorithm utilizing them need to ensure the boundaries are respected? Can the background of the tiles be recalled to erase mistaken trespasses ?

**Comment by cormullion** [comment]
I think most basic 2D tasks are possible, it's more a matter of how much code you're prepared to write... :)

![juliapool](https://user-images.githubusercontent.com/52289/36373618-93b7614e-1560-11e8-8c4b-149c36e2079d.gif)

[code](https://gist.github.com/cormullion/9c3676b8e456600c33011df03f978c42)

Formatting the text is one of those tasks where I can imagine having to write a bit of code, simply because you're having to position each piece of text intellligently. No tables or legends in Cairo, so you'd have to roll your own.

**Comment by mantzaris** [comment]
Thank you for this. I see that you used 'Tiles'. Would the 'Partition' function deliver anything different?

**Comment by mantzaris** [comment]
Theoretically could you use the 'origin()' function to reset the coordinate reference point/

**Comment by cormullion** [comment]
The difference between Tiles and Partition is really just whether you want to specify the quantity of panes or their dimensions. (You can’t specify both at the same time, oddly enough...) But they’re both just simple iterators to help with positioning and dimensions, they’re not ‘smart’ graphic objects with properties such as ‘background’ color schemes.

I believe the `background()` function works with the current clipping region, which is either the whole drawing, or the current clipping path, if you’ve set one up. So to change the background color of a pane, you can define a rectangular clipping region and use `background()`, or just draw a box and fill it.

`origin()` takes you to the original center of the drawing, not always useful.

Cairo/Luxor is fairly low-level!

The [Compose.jl](https://github.com/GiovineItalia/Compose.jl) package is perhaps more what you think a graphics package should be - being aligned more with the needs of statistical graphics, R’s Grammar of Graphics, plotting and visualisation tools, Gadfly, declarative graphics, and so on. Not my thing (hence Luxor) but v. popular with the academic side of the Julia community because of the higher-level focus.
