### ISSUE TITLE
settext doesn't use fontsize()

### ISSUE THREAD

**Issue by Wikunia** [JuliaGraphics/Luxor.jl#52]
I'm currently using Luxor for my [CodePoster](https://github.com/Wikunia/CodePoster) project. I wanted to try to set text with different colors for different parts of a text (syntax highlighting) by using `settext`. I realized that `settext` doesn't use the fontsize specified by `fontsize`. This is unexpected behavior for me. I think if not specified directly like `<span font='26'>text</span>` it should use the fontsize specified by the fontsize command.

**Comment by cormullion** [comment]
Hi! I saw that project, it looks great!  

I think the problem here is that there are two simultaneously available text APIs in Cairo. In Luxor, `fontsize` and `fontface` are the Toy  API, and `settext` and `setfont`are the so-called Pro API. They're different Cairo calls and have different behaviours with respect to accessing system fonts. If you mix them, you'll get unexpected results. (I switch between them, because sometimes the Pro API gets more symbols correct, but the Toy API accesses macOS fonts better.

We would love to have someone provide a full API to Cairo's Pro text API, complete with Pango support, but that's too advanced for me... :)

**Comment by Wikunia** [comment]
Thanks for your fast response. Yeah setting `fontface` and `fontsize` for `textextents` and then `setfont` and `settext` for the text works.

**Comment by cormullion** [comment]
Yes, `textextents` is the Toy API one that would be mirrored in the Pro API with lots of `glyph-` functions (https://www.cairographics.org/manual/cairo-text.html) , but those need adding to Cairo.jl by somebody... :)
