### ISSUE TITLE
How to subtract one path from another

### ISSUE THREAD

**Issue by sethaxen** [JuliaGraphics/Luxor.jl#72]
I have two shapes and would like to use one to make part of another transparent. This is in effect the opposite of `clip`. Can Luxor do this?

For example, in the below example

```julia
@png begin
    setcolor("red")
    rect(Point(-100, 0), 200, 200, :fill)
    setcolor("black")
    circle(Point(0.0, 0.0), 100, :fill)
end
```

I would like to subtract the circle from the square.

**Comment by cormullion** [comment]
Hi Seth! You may be able to do things with paths and subpaths (holes). This is quite ugly, but once wrapped up in a function you can avoid looking at it :)

```
@draw begin
    background("orange")
    sethue("grey20")
    fontsize(50)
    text("is this working?", O + (0, 50), halign=:center)
    rect(Point(-100, 0), 200, 200, :path)
    newsubpath()
    rotate(π)
    carc(O, 100, 0, π, :path)
    sethue("red")
    fillpath()
end
```

<img width="405" alt="Screenshot 2019-11-12 at 10 20 42" src="https://user-images.githubusercontent.com/52289/68663147-18c29680-0536-11ea-8b91-5c04665bedf7.png">

**Comment by sethaxen** [comment]
Thanks for the quick response! The example I showed was just a simple toy. The real case I'm interested in is subtracting text from a shape. e.g. in the example you showed, can the text be subtracted from the rectangle using subpaths?

**Comment by cormullion** [comment]
Sounds tricky - I'm not quite sure whether that would be possible or easy. Cairo is more a rendering system than a modelling one... often you're creating the appearance of things rather than creating the actual things and then drawing them. So you might be able to convey the illusion of what you want...

<img width="586" alt="Screenshot 2019-11-12 at 10 57 13" src="https://user-images.githubusercontent.com/52289/68666168-4cec8600-053b-11ea-895f-e0056c049331.png">

**Comment by cormullion** [comment]
Hi Seth - did you get this working? Need any more help? Or perhaps we can close it now...

**Comment by sethaxen** [comment]
Sorry for the delayed reply. No, I wasn't able to get it working, but I went with a different approach and don't need this now. Thanks for your help!
