### ISSUE TITLE
Overlapping lines in Luxor.box with rounded corners

### ISSUE THREAD

**Issue by AlexRogersCS** [JuliaGraphics/Luxor.jl#73]
The box function with a corner radius:

`function box(centerpoint::Point, width, height, cornerradius, action::Symbol=:stroke)`

in shapes.jl creates a box with overlapping lines due to the superfluous:

`line(p1start)`

instruction on line 145.

**Comment by cormullion** [comment]
Hi Alex. That's some Sherlockian-level sleuthing! I'd never have spotted it... :)

**Comment by AlexRogersCS** [comment]
My SVG viewer showed it as a very slightly thicker line at some zoom levels. I'm using Luxor to generate files for a laser cutter so the actual path followed by the laser is quite important. Thanks for developing Luxor.

**Comment by cormullion** [comment]
Thanks - cool stuff! This should be fixed in the master branch (https://github.com/JuliaGraphics/Luxor.jl/commit/4384e7a51b65768924686ada4d4b0d85d2f12663) now , due for release soon (although I might have made some mistakes in the Project.toml stuff, which I don't fully understand :)).

Your application may well reveal further infelicities in the code - your contributions will be very welcome!
